const languages = {
  en: [
    "Getting Started",
    "Tutorial",
    "Usage Guide",
    "FAQ",
    "Best Practices",
    "A Predictable State Container for JS Apps",
    "GET STARTED",
    "Predictable",
    "Redux helps you write applications that behave consistently , run in different environments (client, server, and native), and are easy to test.",
    "Centralized",
    "Redux helps you write applications that behave consistently , run in different environments (client, server, and native), and are easy to test.",
    "Debuggable",
    "Redux helps you write applications that behave consistently , run in different environments (client, server, and native), and are easy to test.",
    "Flexible",
    "Redux helps you write applications that behave consistently , run in different environments (client, server, and native), and are easy to test.",

    "Other Libraries from the Redux Team",
    "Official React bindings for Redux",
    "The official, opinionated, batteries-included toolset for efficient Redux development",

    "Docs",
    "Getting Started",
    "Usage Guide",
    "Tutorial",
    "FAQ",
    "API Reference",
    "Community",
    "Reactiflux Discord",
    "Stack Overflow",
    "Feedback",
    "More",
    "Copyright © 2015–2023 Dan Abramov and the Redux documentation authors.",
  ],
  az: [
    "Başlanğıc",
    "Dərslik",
    "İstifadə qaydası",
    "Suallar",
    "Praktika",
    "JS Tətbiqləri üçün proqnozlaşdırıla bilən Dövlət Konteyneri",
    "BAŞLAMAQ",
    "Texmin",
    "Redux ardıcıl davranan, müxtəlif mühitlərdə (müştəri, server və yerli) işləyən və sınaqdan keçirilməsi asan olan proqramlar yazmağa kömək edir.",
    "Mərkəzləşdirilmiş",
    "Redux ardıcıl davranan, müxtəlif mühitlərdə (müştəri, server və yerli) işləyən və sınaqdan keçirilməsi asan olan proqramlar yazmağa kömək edir.",
    "Uygunlaşabilen",
    "Redux ardıcıl davranan, müxtəlif mühitlərdə (müştəri, server və yerli) işləyən və sınaqdan keçirilməsi asan olan proqramlar yazmağa kömək edir.",
    "Çeviklik",
    "Redux ardıcıl davranan, müxtəlif mühitlərdə (müştəri, server və yerli) işləyən və sınaqdan keçirilməsi asan olan proqramlar yazmağa kömək edir.",

    "Redux komandasının digər kitabxanaları",
    "Redux üçün rəsmi reaksiya bağlamaları",
    "Redux-un səmərəli inkişafı üçün rəsmi, rəyli, batareyalarla təchiz edilmiş alətlər dəsti",

    "Sənədlər",
    "Başlanğıc",
    "İstifadə qaydası",
    "Dərslik",
    "Suallar",
    "API Referansı",
    "İcma",
    "Reaktif elaqe",
    "Daşma",
    "Əlaqə",
    "Daha çoxu",
    "Copyright © 2015–2023 Dan Abramov və Redux sənədlərinin müəllifləri.",
  ],
};

export { languages };
